[package]
name = "ilm-catppuccin"
version = "1.1.2"
compiler = "0.11.0"
entrypoint = "lib.typ"
repository = "https://github.com/Quantalabs/ilm"
authors = ["Muhammad Talal Anwar <@talal>", "Arvind Venkatesh <@quantalabs>"]
license = "MIT-0"
description = "Catppuccin themed, versatile, and minimal template for non-fiction writing. Ideal for class notes, reports, and books."
keywords = ["notes", "script", "report", "book", "novel", "non-fiction", "running footer", "class", "lecture", "catppuccin"]
categories = ["book", "report"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
